apiVersion: apps/v1
kind: Deployment
metadata:
  name: fapi-k8s
  labels:
    app: fapi-k8s
spec:
  selector:
    matchLabels:
      app: fapi-k8s
  template:
    metadata:
      labels:
        app: fapi-k8s
    spec:
      containers:
      - name: fapi-k8s
        image: fapi-k8s:001
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
        envFrom:
        - secretRef:
            name: fapi-k8s
        resources:
          requests:
            memory: 512Mi
            cpu: 500m
          limits:
            memory: 1024Mi
            cpu: 800m
---
apiVersion: v1
kind: Service
metadata:
  name: fapi-k8s
spec:
  selector:
    app: fapi-k8s
  ports:
    - name: fapi-k8s
      protocol: TCP
      port: 8000
      targetPort: 8000
